### PR TITLE
Add onOverlayClose prop and implement graceful fallback.

### PR DESCRIPTION
**Pull request by 722C**
With the current setup, closing the alert via the overlay does not call `props.onClose`.  Since the logic is already fully in place in the `closeSimplert` method, it makes sense to simply reutilize that functionality.

### CODE REVIEW

**Comment by mazipan** [comment]
I don't think its good to make `onClose` triggered when close overlay. In general use case we only wanna close alert without any function triggered.
If you need custom function when you close via overlay click, maybe we should add one `props` instead use existing `onClose`.
`onClose` should be triggered only when we close via button close.

Oh ya, this project inspired by [vue2-simplert](https://github.com/mazipan/vue2-simplert), maybe you can take a look more complete demo from this repo [here](https://mazipan.github.io/vue2-simplert/), you can also see more complete wiki [here](https://github.com/mazipan/vue2-simplert/wiki)

How do you think @722C ?

**Comment by 722C** [comment]
I will admit, I haven't used Vue much at all, but I do use React frequently.  Here is my opinion:

I could see value in creating a separate prop for when the alert is closed via the overlay, but with this being a controlled React component (i.e. when the alert shows) in order for the alert to stay closed, the parent component needs to change the `showSimplert` prop to `false`, or the alert will open on the next update.

Given that, it would make sense to have it check to see if there is an `onOverlayClose` prop and use that if it is available, but fall back to the normal `onClose` if `onOverlayClose` was not provided.  This means that the user could provide an empty function if they want to keep the current behavior or provide a different function if they want different functionality, but the alert would be better behaved if they do not provide an `onOverlayClose`.

Another option to control whether or not `onClose` is called when the alert is closed via the overlay would be to have a boolean prop.  This could be done with or without adding an `onOverlayClose` prop.

Here is a CodeSandbox that demonstrates what I am talking about in regards to the alert reopening: https://codesandbox.io/s/v8v3pqz793

To have an example of what I am seeing, open the alert with the `Show Alert` button, and then close the alert by clicking the overlay.  From there (`showAlert` should be `true` at this point), click the `Increase Value` button.

If the alert is closed with the `Close` button, we are able to set the `showSimplert` prop back to `false`, which means it doesn't open again until you click `Show Alert`.

**Comment by mazipan** [comment]
It is sound good :+1: 
But before you create pull request, do you mind to pull again the newest code.
Because before this someone has created pull request to format the code.

Thanks anyway for your help.

**Comment by 722C** [comment]
@mazipan, I forgot to notify you before (I pushed up the changes in an airport before a long flight), but this should be good to go.

**Pull request merged**
